export {
  AUTO_REGEN_INTERVAL_SECONDS,
  BASE_LEVEL_UP_HEAL,
  addGoldenEggs,
  DEFAULT_META_PROFILE,
  EMPTY_META_UPGRADES,
  getMetaUpgradeBaseLabel,
  getMetaUpgradeBonus,
  getMetaUpgradeBonusLabel,
  getMetaUpgradeCost,
  getMetaUpgradeMaxLevel,
  getMetaResetRefund,
  getMetaUpgradeSpentCost,
  META_UPGRADE_DEFS,
  normalizeMetaProfile,
  normalizeMetaUpgrades,
  purchaseMetaUpgrade,
  resetMetaUpgrades,
} from "./definitions";
export { loadMetaProfile, saveMetaProfile } from "./storage";
